Django_CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("profile/",include('ProfileApp.urls')),
]

ProfileApp/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings


# namespace
app_name = 'profileapp'

urlpatterns = [

    # Function Based View
    path('', views.profileList, name='profile_list'),
    path('create/', views.profileCreate, name='profile_create'),
    path('<int:pk>/', views.profileDetail, name='profile_detail'),
    path('<int:pk>/update/', views.profileUpdate, name='profile_update'),
    path('<int:pk>/delete/', views.profileDelete, name='profile_delete'),
    path('<int:pk>/condelete/',views.confirmDelete,name='profile_condelete')


    # path('', views.ProfileListView.as_view(), name='profile_list'),
    # path('create/', views.ProfileCreateView.as_view(), name='profile_create'),
    # path('<int:pk>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    # path('<int:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    # path('<int:pk>/delete/', views.profile_delete_view, name='profile_delete'),
    # path('<int:pk>/condelete/', views.confirm_delete_view, name='profile_condelete'),




]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProfileApp/models.py
from django.db import models

# Create your models here.

class genderChoice(models.TextChoices):
    choice1='m',"Male"
    choice2='f',"Female" # In Each choice: The first element is the actual value stored in the database, while the second element is the human-readable display value.

class Profile(models.Model):
    firstName=models.CharField(max_length=50,verbose_name="First Name",null=False)
    lastName=models.CharField(max_length=50,verbose_name="Last Name",null=True)
    age=models.IntegerField(null=True)
    dateOfBirth=models.DateField(null=True)
    gmail=models.EmailField(max_length=254,unique=True,verbose_name="Gmail")
    gender=models.CharField(max_length=1,choices=genderChoice.choices)
    profilePicture=models.ImageField(upload_to='Profile/Pictures/',max_length=50)
    cv=models.FileField(upload_to='Profile/Files/',max_length=50)
    shortVideo=models.FileField(upload_to='Profile/Video',max_length=50)
    description=models.TextField(max_length=500,null=True)

ProfileApp/views.py
# Create your views here.

# ----------------------- Function Based View---------------------------

from django.shortcuts import render, redirect, get_object_or_404
from .profileForm import ProfileForm
from django.urls import reverse
from django.http import HttpResponse
from .models import Profile
import os




def profileCreate(request):
    if request.method=='POST':
        pform=ProfileForm(request.POST,request.FILES)
        print(pform)
        if pform.is_valid():
            pform.save()
            return redirect(reverse('profileapp:profile_list'))
    else:
        pform= ProfileForm()
    return render(request,'profile/create_profile.html',{'form':pform})

# Retrieve task list
def profileList(request):
    prdata = Profile.objects.all()
    return render(request, "profile/profile_list.html", { "data": prdata})

# Update a single task
def profileUpdate(request, pk):
    prdata = get_object_or_404(Profile, pk=pk)
    if request.method == 'POST':
        form = ProfileForm(instance=prdata, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("profileapp:profile_detail", args=[pk,]))
    else:
        form = ProfileForm(instance=prdata)

    return render(request, "profile/create_profile.html", { "form": form, "object": prdata})

# Retrieve a single task
def profileDetail(request, pk):
    prdata = get_object_or_404(Profile, pk=pk)
    return render(request, "profile/profile_detail.html", { "data": prdata })


def profileDelete(request, pk):
    #prdata = get_object_or_404(Profile, pk=pk)
    prdata=Profile.objects.filter(pk=pk).first()
    if prdata:
        return redirect(reverse('profileapp:profile_condelete',args=[pk]))
    
    return redirect(reverse("profileapp:profile_list"))

def confirmDelete(request,pk):
    prdata=Profile.objects.filter(pk=pk).first()
    if request.method=='POST':
        if prdata:
            if prdata.profilePicture:
                path = prdata.profilePicture.path
                if os.path.exists(path):
                    os.remove(path)

            if prdata.cv:
                path = prdata.cv.path
                if os.path.exists(path):
                    os.remove(path)

            if prdata.shortVideo:
                path = prdata.shortVideo.path
                if os.path.exists(path):
                    os.remove(path)

            prdata.delete()
            return redirect(reverse('profileapp:profile_list'))
    return render(request,'profile/profile_confdelete.html',{'data':prdata})


# ---------------------------------------------------------------------


# --------------------------- Class Based View -------------------------
"""
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from .profileForm import ProfileForm
from .models import Profile

class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profile/create_profile.html'
    success_url = reverse_lazy('profileapp:profile_list')

class ProfileListView(ListView):
    model = Profile
    template_name = 'profile/profile_list.html'
    context_object_name = 'data'

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profile/profile_detail.html'
    context_object_name = 'data'

class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profile/create_profile.html'
    context_object_name = 'object'
    success_url = reverse_lazy('profileapp:profile_list')

import os
from django.urls import reverse_lazy
from django.views.generic import View, RedirectView, TemplateView
from django.shortcuts import redirect, get_object_or_404
from .models import Profile
from django.shortcuts import render

class ProfileDeleteView(RedirectView):
    def get_redirect_url(self, pk):
        profile = get_object_or_404(Profile, pk=pk)
        return reverse_lazy('profileapp:profile_condelete', args=[profile.pk])

class ConfirmDeleteView(View):
    template_name = 'profile/profile_confdelete.html'

    def get(self, request, pk):
        profile = get_object_or_404(Profile, pk=pk)
        return render(request, self.template_name, {'profile': profile})

    def post(self, request, pk):
        profile = get_object_or_404(Profile, pk=pk)
        if profile.profilePicture:
            path = profile.profilePicture.path
            if os.path.exists(path):
                os.remove(path)
        
        if profile.cv:
            path = profile.cv.path
            if os.path.exists(path):
                os.remove(path)
        
        if profile.shortVideo:
            path = profile.shortVideo.path
            if os.path.exists(path):
                os.remove(path)

        profile.delete()
        return redirect(reverse_lazy('profileapp:profile_list'))

profile_delete_view = ProfileDeleteView.as_view()
confirm_delete_view = ConfirmDeleteView.as_view()
"""

ProfileApp/templates/profile/create_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Edit Profile {% else %} Create New Profile {% endif %}</title>
</head>
<body>
<h3>{% if object %}Edit Profile {% else %} Create New Profile {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</body>
</html>

ProfileApp/templates/profile/profile_confdelete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ data.firstName }}"?</p>
    <input type="submit" value="Confirm" />
</form>

ProfileApp/templates/profile/profile_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile Detail</title>
</head>
<body>
<p> Task Name: {{ data.firstName }} | <a href="{% url 'profileapp:profile_update' data.id %}">Update</a> |
    <a href="{% url 'profileapp:profile_delete' data.id %}">Delete</a>
</p>
<p> Task Status: {{ data.get_gender_display }} </p>
<p> <a href="{% url 'profileapp:profile_list' %}">View All Profile</a> |
    <a href="{% url 'profileapp:profile_create'%}">New Profile</a>
</p>
</body> 
</html>

ProfileApp/templates/profile/profile_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile List</title>
</head>
<body>
<h3>Profile List</h3>
{% for dta in data %}
    <p>{{ forloop.counter }}. {{ dta.firstName }} {{ dta.lastName}} - {{ dta.gmail }} - {{ dta.get_gender_display }}
        (<a href="{% url 'profileapp:profile_update' dta.id %}">Update</a> |
        <a href="{% url 'profileapp:profile_delete' dta.id %}">Delete</a>)
    </p>
{% endfor %}

<p> <a href="{% url 'profileapp:profile_create' %}"> + Add A New Profile</a></p>
</body>
</html>